name = "backend"
compatibility_date = "2023-12-01"

 [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzY3MjY4NjItY2QyNC00NDI3LTllMTgtYWUzNDllNWEwOWJkIiwidGVuYW50X2lkIjoiZTRjMjZkODJmMzA5OThkYTA0NmE5MDdkYmQyMjE1ZmExYzE0YjExN2ZkOTMyYmFhZWY1ZDYyN2IxZjNkZTFhMCIsImludGVybmFsX3NlY3JldCI6ImE5ZDYyNWM2LTQyMzctNDlhNi05YTZkLWE0NTllNDRlNDliZCJ9.CkyLV7vRhyjLMCLpCNmX3M1EoCn7vFQgcuPIlK_1Rpw"
JWT_SECRET="dMUQPd6SVQPMIsRBS6Gr1hMD8yLapxO8X6HSqntfOLo"